FROM node:18-bullseye

RUN apt-get update && apt-get install -y \
    libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon0 libxcomposite1 \
    libxdamage1 libxfixes3 libxrandr2 libgbm1 libasound2 libpangocairo-1.0-0 libpango-1.0-0 \
    libcairo2 wget && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./node/ /app/

RUN npm install

EXPOSE 3000
CMD ["node", "server.js"]
