FROM php:8.3-fpm

ARG UID=1000
ARG GID=1000
ARG USER=mahdi

USER root

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    zip \
    supervisor \
    libsqlite3-dev \
    libpq-dev \
    libzip-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libicu-dev \
    libpng-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install \
        pdo \
        pdo_mysql \
        pdo_sqlite \
        zip \
        gd \
        pcntl \
        intl

RUN pecl install xdebug && docker-php-ext-enable xdebug
RUN pecl install redis && docker-php-ext-enable redis

RUN apt-get update && apt-get install -y \
    nodejs \
    npm \
    && rm -rf /var/lib/apt/lists/*

COPY --from=composer:2.6 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

RUN mkdir -p /var/log/supervisor

# Copy the entrypoint script
COPY ./entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

EXPOSE 9000

RUN groupadd -g ${GID} ${USER} \
 && useradd -m -u ${UID} -g ${USER} ${USER} \
 && usermod -aG ${USER} www-data

# Change the default command to run the entrypoint script
CMD ["supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]