version: '3.8'

services:
  php:
    image: php:8.3-fpm
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks:
      - app-network
    environment:
      - SERVER_NAME=${SERVER_NAME}
    env_file:
      - ./src/.env
    container_name: zitazi-php

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network
    environment:
      - SERVER_NAME=${SERVER_NAME}
    env_file:
      - ./src/.env
    container_name: zitazi-nginx

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: zitazi
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - app-network
    container_name: zitazi-mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"  # Exposing port 8080 for phpMyAdmin web interface
    environment:
      MYSQL_ROOT_PASSWORD: 123  # This should match your MySQL root password
      PMA_HOST: mysql  # Host for phpMyAdmin to connect to the MySQL container
    networks:
      - app-network
    depends_on:
      - mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    networks:
      - app-network
    container_name: zitazi-redis

  horizon:
    image: php:8.3-fpm
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
    depends_on:
      - mysql
      - redis
    command: php artisan horizon
    container_name: zitazi-horizon

volumes:
  mysql:
  redis:

networks:
  app-network:
