FROM node:18-bullseye

RUN apt-get update && apt-get install -y \
    libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon0 libxcomposite1 \
    libxdamage1 libxfixes3 libxrandr2 libgbm1 libasound2 libpangocairo-1.0-0 libpango-1.0-0 \
    libcairo2 wget && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./node/package.json /app/package.json

RUN npm install
RUN npm install --save-dev nodemon

COPY ./node/src /app/src

EXPOSE 3000
