FROM php:8.3-fpm

USER root

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    zip \
    supervisor \
    libsqlite3-dev \
    libpq-dev \
    libzip-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libicu-dev \
    libpng-dev \
    nodejs \
    npm \
    && rm -rf /var/lib/apt/lists/* \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install \
        pdo \
        pdo_mysql \
        pdo_sqlite \
        zip \
        gd \
        pcntl \
        intl


RUN pecl install redis \
    && docker-php-ext-enable redis


COPY --from=composer:2 /usr/bin/composer /usr/bin/composer


WORKDIR /var/www/html


# PHP configuration
COPY infra/php.ini /usr/local/etc/php/php.ini


#################################################
# Composer dependencies cache layer
#################################################

COPY ./src/composer.json ./src/composer.lock ./


RUN composer install \
    --no-dev \
    --no-interaction \
    --prefer-dist \
    --optimize-autoloader \
    --classmap-authoritative \
    --no-scripts



#################################################
# Node dependencies cache layer
#################################################

COPY ./src/package.json ./src/package-lock.json ./


RUN npm ci


#################################################
# Application source
#################################################

COPY ./src .


#################################################
# Laravel post composer scripts
#################################################

RUN php artisan package:discover --ansi \
    && php artisan filament:upgrade



#################################################
# Frontend build
#################################################

RUN npm run build \
    && npm prune --omit=dev



#################################################
# Permissions
#################################################

RUN chown -R www-data:www-data \
        storage \
        bootstrap/cache \
    && chmod -R 775 \
        storage \
        bootstrap/cache


USER www-data