[PHP]
memory_limit = 2G
upload_max_filesize = 100M
post_max_size = 100M
max_execution_time = 300

;[xdebug]
;zend_extension = xdebug.so
;xdebug.mode = debug
;xdebug.start_with_request = yes
;xdebug.client_host = host.docker.internal
;xdebug.client_port = 9003
;xdebug.log_level = 0
;xdebug.idekey = docker
