# ============================================================
# 1. Frontend
# ============================================================

FROM node:20-bookworm-slim AS frontend

WORKDIR /app

COPY ./src/package.json ./src/package-lock.json ./

RUN npm ci

COPY ./src .

RUN npm run build


# ============================================================
# 2. Composer dependencies
# ============================================================

FROM php:8.3-cli AS composer

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /app

COPY ./src/composer.json ./src/composer.lock ./

RUN composer install \
    --no-dev \
    --no-interaction \
    --prefer-dist \
    --optimize-autoloader \
    --classmap-authoritative \
    --no-scripts


# ============================================================
# 3. Production PHP
# ============================================================

FROM php:8.3-fpm AS production

USER root

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    zip \
    supervisor \
    libsqlite3-dev \
    libpq-dev \
    libzip-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libicu-dev \
    libpng-dev \
    && rm -rf /var/lib/apt/lists/* \
    && docker-php-ext-configure gd \
        --with-freetype \
        --with-jpeg \
    && docker-php-ext-install \
        pdo \
        pdo_mysql \
        pdo_sqlite \
        zip \
        gd \
        pcntl \
        intl

RUN pecl install redis \
    && docker-php-ext-enable redis

WORKDIR /var/www/html

COPY ./infra/php.ini /usr/local/etc/php/php.ini

COPY ./src .

COPY --from=composer /app/vendor ./vendor

COPY --from=frontend /app/public/build ./public/build

RUN php artisan package:discover --ansi && php artisan filament:upgrade

RUN chown -R www-data:www-data \
        storage \
        bootstrap/cache \
    && chmod -R 775 \
        storage \
        bootstrap/cache

USER www-data