groups:

  - name: server
    rules:
      - alert: TestTelegramAlert
        expr: vector(1)
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: "Test alert"
          description: "This is a Telegram alert test."

      - alert: HighCPUUsage
        expr: |
          100 - (
            avg by(instance) (
              rate(node_cpu_seconds_total{mode="idle"}[5m])
            ) * 100
          ) > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage on {{ $labels.instance }} has been above 90% for 5 minutes."

      - alert: HighMemoryUsage
        expr: |
          (
            1 -
            node_memory_MemAvailable_bytes /
            node_memory_MemTotal_bytes
          ) * 100 > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage on {{ $labels.instance }} has been above 90% for 5 minutes."

      - alert: LowDiskSpace
        expr: |
          (
            node_filesystem_avail_bytes{fstype!~"tmpfs|overlay"}
            /
            node_filesystem_size_bytes{fstype!~"tmpfs|overlay"}
          ) * 100 < 10
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Low disk space"
          description: "Filesystem {{ $labels.mountpoint }} has less than 10% free space."

      - alert: NodeDown
        expr: up{job="node"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Node Exporter is down"
          description: "Prometheus cannot scrape Node Exporter on {{ $labels.instance }}."