name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH to VPS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            set -e
            cd ~/zitazi

            echo "🔄 Pulling latest code..."
            git pull origin master
            
#            echo "🧹 Running artisan migrate inside container..."
#            docker exec zitazi-php php artisan migrate --force